# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Bots

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: 'Cleanup Workspace'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      run: dotnet publish -f net9.0 -c release -r linux-x64 --self-contained
    - name: Stop Bots
      run: |
#          sudo systemctl stop GiverOfHeadPatsBot.service
#          sudo systemctl stop RePlayBot.service
          sudo systemctl stop JasminePostsBot.service
    - name: Move Files
      run: |
          cp -R ./Discord.HeadPat/bin/Release/net9.0/linux-x64/publish/* /_DATA/dubya/BoobaGenerator/DiscordBot/
          cp -R ./Discord.Michiru/bin/Release/net9.0/linux-x64/publish/* /_DATA/dubya/Ruby/DiscordBot/
          cp -R ./Discord.JasPosts/bin/Release/net9.0/linux-x64/publish/* /_DATA/dubya/RePlay/DiscordBot/